Regex = ElemBase *

ElemBase = CharNonRange | Range
RangeRightable = CharEndRange
Range = Char <'-'> CharEndRange
CharNonRange = Char ! ('-' RangeRightable)
Char = PlainChar | EscapedChar
CharEndRange = PlainChar | EscapedChar
PlainChar = #"[-x]"
Dash = '-'


(** BASE CHARACTER STUFFS **)

EscapedChar = ControlChar

ControlChar = <'\\c'> (<'\\'> #"(?s)." | ! '\\' #"(?s).")
